### ISSUE TITLE
Replace cypress email.cy.js with PyTest integration tests.

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#393]

**Comment by cyplas** [comment]
@danmash I've added new or adapted existing tests (as much was already implemented) for all the email cypress tests I think. But I'm not sure about a couple of things. First, there were existing pytest tests that were structured a little differently than in other parts of the app (e.g., multiple explicit tests of the same route inside the same function rather than use of pytest.mark.parametrize, and I didn't restructure. Do you think this is ok, or should they be restructured? Second, I'm not sure how much of the cypress stuff can now be safely purged from the repo, so I haven't deleted any cypress code. Is there still need for cypress code, in being used for stuff other than the e2e tests, such as github integration? As a result, I haven't made a PR yet.

**Comment by danmash** [comment]
@cyplas it's fine to have unit tests for functions and integration tests for the route. it's fine if these tests are overlaps. 

Please proceed with removing all cypress/js files and configs and update CI configuration in .circleci folder
https://github.com/ClimateMind/climatemind-backend/issues/406
