### ISSUE TITLE
Replace cypress login.cy.js with PyTest integration tests.

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#396]

**Comment by Nehemiah60** [comment]
Thanks Dan

**Comment by danmash** [comment]
@Nehemiah60 do you need any help on this?

**Comment by cyplas** [comment]
@danmash I could take this, but I'm not sure what to make of the rateLimit stuff (which also occurs in email.cy.js and register.cy.js). I understand that this must be connected to the `@limiter.limit` in routes.py, but it's odd to me that the limit would ever be reached when running the tests, and even if it did, then these tests wouldn't be successfully verifying what they really should be verifying. Am I missing something, or should we drop these checks during the test rewrites?

**Comment by danmash** [comment]
> but it's odd to me that the limit would ever be reached when running the tests

@cyplas try it. Create a test with a loop inside and try to reach the limit. If you succeed then keep the test and mock `limiter` in other tests to avoid duplications. 
if you won't succeed with the "limit test" then ignore these tests. 
Does it make sense?

**Comment by cyplas** [comment]
> @cyplas try it. Create a test with a loop inside and try to reach the limit. If you succeed then keep the test and mock `limiter` in other tests to avoid duplications. if you won't succeed with the "limit test" then ignore these tests. Does it make sense?

Ok. On first attempt it's not working, but it may have something to do with app.auth.routes.ip_whitelist along with my newness to mocking, which it's high time I address anyway. :)

**Comment by cyplas** [comment]
It seems that there are some issues with testing flask limiters using unit tests, as my loop isn't yielding the expected results, even if I disable ip_whitelist (which I can see is otherwise called), set limit values to 1 or 0 (which I can see works testing outside of python), or try a couple of the workarounds mentioned here (https://github.com/alisaifee/flask-limiter/issues/147). It's probably possible in some way, but I think I'll skip it here and focus on the main stuff.
